# Generated by Django 3.0.3 on 2020-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='text_file_content',
            field=models.TextField(blank=True, verbose_name='If this field has a content, file.txt tab will be shown'),
        ),
    ]
