# Generated by Django 3.0.3 on 2020-05-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_track_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_units', to='courses.Track'),
        ),
    ]
