# Generated by Django 3.0.3 on 2020-05-15 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200511_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_lessons', to='courses.Unit'),
        ),
    ]
