# Generated by Django 4.1.4 on 2022-12-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200515_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='input_error_text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='input_should_contain',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='input_should_not_contain',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_error_text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_should_contain',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_should_not_contain',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text_file_content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='unit_test',
        ),
    ]
