# Generated by Django 4.1.4 on 2022-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_exercise_input_should_contain_error_msg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='output',
            new_name='console_output',
        ),
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error message'),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
