# Generated by Django 4.1.4 on 2023-01-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_alter_submission_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='track_subscriptions', to='courses.track'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'track')},
        ),
    ]
