# Generated by Django 4.1.4 on 2023-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    def dedupe_subscriptions(apps, schema_editor):
        Subscription = apps.get_model('courses', 'Subscription')
        subs_to_exclude = Subscription.objects.all().distinct(
            'track__id', 'user__id').values_list('id', flat=True)
        to_delete = Subscription.objects.exclude(id__in=subs_to_exclude)
        to_delete.delete()

    dependencies = [
        ('courses', '0016_create_subscriptions_data_migration'),
    ]

    operations = [
    migrations.RunPython(dedupe_subscriptions),
    ]
